# Deploy snapshots to Sonatpe OSS repository

name: Deploy

on:
  # *** Temporarily enable this for all branches to be able to test it on the github-actions branch - workflow_run only works on default branch ***
  push:
    branches-ignore:
      - 'master'
      - 'experimental/**'
#  workflow_run:
#    workflows:
#      - Verify
#    branches:
#      - $default-branch
#    types: 
#      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure git credentials
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'Tobias Richter'
          email: 'tobias.richter@diva-e.com'
          token: '${{ secrets.GH_SITE_DEPLOY_PAT }}'

      # Debug git config
      - name: Set git config
        run: |
          git config --global user.email "tobias.richter@diva-e.com"
          git config --global user.name "Tobias Richter"
          git config user.email "tobias.richter@diva-e.com"
          git config user.name "Tobias Richter"

      # Debug git config
      - name: Debug git config
        run: |
          git config --global --list
          git config --list


      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Set up dependency cache
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build, deploy to ossrh, deploy site to Github Pages, generate and stage site
      - name: Build, verify, deploy, generate site
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean site site:stage

      # Deploy site to Github Pages
      - name: Deploy site
        env:
          GITHUB_USERNAME: ${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          GITHUB_PAT: ${{ secrets.GH_SITE_DEPLOY_PAT }}
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B scm-publish:publish-scm -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }} -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}