# Deploy snapshots to Sonatype OSS repository and deploy site to GitHub Pages

name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure GIT
        run: |
          git config --global user.email "${{ secrets.GH_SITE_DEPLOY_EMAIL }}"
          git config --global user.name "${{ secrets.GH_SITE_DEPLOY_NAME }}"

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Build, verify, deploy, generate site
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean deploy site

      - name: Stage and deploy site
        run: >
          ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }}"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
