# Build validation

name: Build

on:
  push:
    branches-ignore:
      - master
      - experimental/**
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - master
      - experimental/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11, 17]
        os: [ubuntu-latest]
        distribution: [temurin]

    steps:
      - name: Maven Build with SonarCloud
        uses: wcm-io-devops/github-action-maven-build-sonar@v1
        with:
          os: ${{ matrix.os }}
          java-version: ${{ matrix.java }}
          maven-executable: ./mvnw
          sonar-run-on-os: ubuntu-latest
          sonar-run-on-java-version: 11
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
